CLI architecture
MariaChizhova/SD-2022 pull request #1
Opened 2022-01-23 18:01 UTC by MariaChizhova

Задание выполнено Чижовой Марией и Потрясаевой Анной

2022-01-25 11:14 UTC, yurii-litvinov requested changes
Это вполне годный первый набросок архитектуры, но нужна ещё одна-две итерации по её детализации. Основные решения о структуре системы более-менее приняты, но дьявол кроется в деталях (в том числе и критически важных для работы всего шелла, так что от них нельзя отмахнуться и сказать "разберёмся при реализации").

2022-01-25 11:14 UTC, yurii-litvinov commented on README.md
> +`main.py` -  файл, в котором реализован основной цикл программы. Он считывает входную строку из терминала и передает ее парсеру.
Вы как-то сразу и без нужды привязываетесь к языку реализации. Архитектуру лучше описывать в абстрактных терминах, типа "компонент", "класс".

2022-01-25 11:14 UTC, yurii-litvinov commented on README.md
> +`parser.py` - парсер выполняет разбор командной строки на список сущностей, которые могут представлять собой: команды, аргументы, объявление переменных или `“|”` - пайплайны. Поддерживает разбор и `‘
Выполняет, а как? Надо примерно описать алгоритм разбора.

2022-01-25 11:14 UTC, yurii-litvinov commented on README.md
> +Далее происходит подстановка переменных окружения (`substitution.py`). Вместо выражений, обернутых в `‘’` подстановка не осуществляется.
Тоже, "происходит подстановка" --- это не многим лучше с точки зрения тех, кто будет это реализовывать, чем "программа хорошо работает". Тем более что тут надо принять критически важные решения --- например, подстановка происходит один раз или пока можем, что со строками вида `"'$x'"`.

2022-01-25 11:14 UTC, yurii-litvinov commented on README.md
> +Далее передаем в `builder` (`pipеline_builder.py`) список сущностей, который последовательно создает команды. На выход получаем список команд. Исполняем их последовательно, при этом содержимое потока
Как я понял, не делается повторная токенизация, тогда пример
```
x=echo hello
$x
```
работать не будет. Что, наверное, допустимо, но нужно это явно зафиксировать и порассуждать на тему преимуществ и недостатков по сравнению с bash-евским подходом.

2022-01-25 11:14 UTC, yurii-litvinov commented on README.md
> +Далее передаем в `builder` (`pipеline_builder.py`) список сущностей, который последовательно создает команды. На выход получаем список команд. Исполняем их последовательно, при этом содержимое потока
А как он создаёт команды?

2022-01-25 11:14 UTC, yurii-litvinov commented on README.md
> +Также есть возможность вызова внешних команд в случае, если введено что-то, что интерпретатор не знает.
О, копипаст из ТЗ :) А _как_ exit завершает работу интерпретатора? :)
Ну и, конечно, а как вызываются внешние программы? И там даже не один архитектурный вопрос, на который надо ответить. Подумайте, про что надо будет подумать :)

2022-01-25 11:14 UTC, yurii-litvinov commented on README.md
> +Файл `commands.py` содержит описание того, как должны исполняться соответствующие команды. Каждая команда представляется отдельным классом, который наследуется от класса `Command`. Каждый класс имеет
А какие у execute параметры и возвращаемый результат? Без указания этого сложно что-либо сказать про перенаправление потоков ввода-вывода

2022-01-25 11:14 UTC, yurii-litvinov commented on README.md
> +Если переменные объявляются в пайплайне или встречается команда `exit`, то они будут проигнорированы.
А про ситуации, когда объявление переменных _не_ будет проигнорировано, ничего не написано. Как переменные представляются, например, как про них узнаёт substitution.py и кто именно обрабатывает присваивание?

2022-01-27 19:35 UTC, MariaChizhova commented
@yurii-litvinov 
Описание архитектуры дополнено.

2022-01-28 10:02 UTC, yurii-litvinov requested changes
Вот, уже можно обсуждать по существу :) Тем не менее, ещё много вопросов. Кстати, можно что-то не исправлять, а просто ответить на комментарий, если считаете, что у вас правильно.

2022-01-28 10:02 UTC, yurii-litvinov commented on README.md
> +Разбиваем строку на список токенов, запускаем на нем алгоритм обработки:
А как разбиваем? Просто посплитить по пробелам ведь не получится.

2022-01-28 10:02 UTC, yurii-litvinov commented on README.md
> +тогда из словаря переменных извлекается значение по ключу, если переменная не определена - пустая строка.
А по какому ключу? Токен "подстановка", судя по написанному выше, это просто `$`. Вот видим токен `$`, что делаем?

2022-01-28 10:02 UTC, yurii-litvinov commented on README.md
> +Всё что находится в одинарных кавычках разбирается как есть и является строкой.
А в двойных? У вас токен может представлять собой строку, и если `'a b c'` токенизируется в токен "строка", то во что токенизируется токен `"a b c"`? Если тоже один токен "строка", то беда, как делать подстановку? Если нет, то как отличить `"a b c"` от `a b c`? Это важно, чтобы передавать команде аргумент с пробелами, например, имя файла в cat

2022-01-28 10:02 UTC, yurii-litvinov commented on README.md
> +Считаем, что название переменной - токен до знака `=`,
А если до знака `=`  больше одного токена? Или 0?

2022-01-28 10:02 UTC, yurii-litvinov commented on README.md
> +Создается экземпляр класса `Command` (`declartion`), который будет записывать в глобальный словарь `{"название переменной": "её вычесленное значение"}`.
```suggestion
Создается экземпляр класса `Command` (`declaration`), который будет записывать в глобальный словарь `{"название переменной": "её вычесленное значение"}`.
```

2022-01-28 10:02 UTC, yurii-litvinov commented on README.md
> +Само значение до этапа вычисления тоже является командой, которую надо будет вычислить, но только если всё выражение присваивания не находится в пайплайне,
Вычислить? То есть `x=cat f.txt` записывает в x _содержимое_ f.txt? Обычные шеллы так не делают, потому что, вообще говоря, подстановка может быть как раз нужна, чтобы собрать команду. Хотя ваш шелл --- ваши правила, но тогда стоит явно написать о том, что семантика у вас такая, и почему это хорошо (типа пры примеров usecase-ов, где это полезно).

2022-01-28 10:02 UTC, yurii-litvinov commented on README.md
> +иначе команда присваивания игнорируется, а потоки ввода-вывода зануляются.
Почему бы тогда не запретить присваивания в пайпе ещё на этапе парсинга? Чтобы ошибку выдавало?

Кстати, тут вы описываете семантику вычисления команды, тогда как речь ещё про парсер идёт

2022-01-28 10:02 UTC, yurii-litvinov commented on README.md
> +Иначе выполняется запуск подпроцесса.
Прямо во время парсинга, что?

2022-01-28 10:02 UTC, yurii-litvinov commented on README.md
> +Каждая команда представляется отдельным классом `CommandName`, который наследуется от абстрактного класса `Command`.
Вот бы диаграмму классов... На словах это как-то тяжело воспринимать

2022-01-28 10:02 UTC, yurii-litvinov commented on README.md
> +* Команда `wc [FILE]` выводит количество строк, слов и байт в последовательности файлов. Для каждого файла информация выводится отдельно, перед ней указывается название соответствующего файла.  Если
Просили wc с одним файлом, это может сэкономить усилия при реализации

2022-01-28 10:02 UTC, yurii-litvinov commented on README.md
> +* Команда `exit` завершает работу интерпретатора, а именно в методе execute вызывается метод exit(). При существовании субпроцессов отправляем им сигнал прерывания и если они не завершились - убиваем
Параллельные субпроцессы можно не поддерживать --- при запуске внешней программы синхронно ждём, пока она завершится. Опять же, чтобы сэкономить усилия.

Кстати, exit --- это библиотечный, который просто прибивает программу? Я бы сказал "никогда-никогда им не пользуйтесь", потому что он делает невозможным переиспользование. Вдруг я захочу ваш шелл использовать в окошке в своей IDE? Пользователь пишет exit, у меня вся IDE закрывается, даже не успев сделать автосохранение файлов, не очень.

2022-01-28 10:02 UTC, yurii-litvinov commented on README.md
> +* Команда `declartion` присваивает значение переменной. Соответственно, ее аргументы - название и значение переменной.
```suggestion
* Команда `declaration` присваивает значение переменной. Соответственно, ее аргументы - название и значение переменной. 
```
Я надеюсь, а то у вас эта опечатка второй раз уже

2022-01-28 10:02 UTC, yurii-litvinov commented on README.md
> +* Команда `outercommand` - вызов внешних команд в случае, если введено что-то, что интерпретатор не знает. Создается новый поток, в котором выполняется процесс требуемой команды.  `stdin` передается
Не-а. А что если внешняя команда --- это java, и она очень хочет узнать JAVA_HOME, который мы выставили в нашем шелле строкой выше? Ну или bash-евсский скрипт, который сам использует переменные окружения?

2022-01-28 10:02 UTC, yurii-litvinov commented on README.md
> +В процессе выполнения каждого шага обрабатываем ошибки.
Позвольте попридираться и спросить "а как" :) Обработка ошибок --- это довольно важный для архитектуры "cross-cutting concern", про который часто забывают

2022-02-03 13:46 UTC, MariaChizhova commented on README.md
> +Разбиваем строку на список токенов, запускаем на нем алгоритм обработки:
Добавили описание.

2022-02-03 13:47 UTC, MariaChizhova commented on README.md
> +тогда из словаря переменных извлекается значение по ключу, если переменная не определена - пустая строка.
Добавили в описание

2022-02-03 13:47 UTC, MariaChizhova commented on README.md
> +Само значение до этапа вычисления тоже является командой, которую надо будет вычислить, но только если всё выражение присваивания не находится в пайплайне,
Мы решили это не поддерживать

2022-02-03 13:52 UTC, MariaChizhova commented on README.md
> +* Команда `exit` завершает работу интерпретатора, а именно в методе execute вызывается метод exit(). При существовании субпроцессов отправляем им сигнал прерывания и если они не завершились - убиваем
Мы имеем ввиду, например, sys.exit() в pyhon, он не закрывает IDE, а просто заканчивает работу:
![image](https://user-images.githubusercontent.com/57176713/152355909-2ca13aa4-5e9d-4a97-80ef-98967f8ee32c.png)

2022-02-03 13:52 UTC, MariaChizhova commented on README.md
> +В процессе выполнения каждого шага обрабатываем ошибки.
Когда у нас происходит какая-то ошибка, бросаем исключение.

2022-02-03 13:55 UTC, MariaChizhova commented
Документация дополнена.
@yurii-litvinov

2022-02-05 11:43 UTC, yurii-litvinov commented on README.md
> +Имеем `ordered dict: {токен:регулярка для него}`. Проходим по порядку по дикту и смотрим, что с текущей позиции регулярка что-то захватывает. Если регулярка что-то съела, то мы распарили токен и начи
Очень жаргонно, но в целом я понял :) Надо как-то гарантировать, что ни один токен не является префиксом для другого, или "есть" токен максимальной длины, но ок

2022-02-05 11:43 UTC, yurii-litvinov commented on README.md
> +тогда из словаря переменных извлекается значение по ключу (все символы после `$`до пробела - название переменной), если переменная не определена - пустая строка.
Я бы сказал "до пробела, кавычек или пайпа", но ваш шелл — ваши правила

2022-02-05 11:43 UTC, yurii-litvinov commented on README.md
> +Имеем `ordered dict: {токен:регулярка для него}`. Проходим по порядку по дикту и смотрим, что с текущей позиции регулярка что-то захватывает. Если регулярка что-то съела, то мы распарили токен и начи
И хотелось бы оные регулярки прямо тут, наверное. Потому что дальше это критично — токен это `$` или `$` с текстом за ним, например. Или хотя бы неформально описать каждый токен.

2022-02-05 11:43 UTC, yurii-litvinov commented on README.md
> +Всё что находится в одинарных кавычках разбирается как есть и является строкой, а в двойных осуществляется проверка: содержится ли подстановка переменной (если есть, то происходит подстановка).
А если их много? А если после подстановки появятся новые кавычки? Или так нельзя? А если нельзя, то почему?

2022-02-05 11:43 UTC, yurii-litvinov commented on README.md
> +Само значение до этапа вычисления тоже является командой, которую надо будет вычислить, но только если всё выражение присваивания не находится в пайплайне,
Разумно, незачем усложнять себе жизнь, если не просят

2022-02-05 11:53 UTC, yurii-litvinov commented on README.md
> +Иначе выполняется запуск подпроцесса - создается экземпляр класса `Command`, который ответственен за запуск подпроцесса. Параллельные подпроцессы не поддерживаются, при запуске внешней программы синх
Опять-таки, описываете семантику исполнения, тогда как речь тут ещё про парсер

2022-02-05 11:53 UTC, yurii-litvinov commented on README.md
> +* Команда `exit` завершает работу интерпретатора, а именно в методе execute вызывается метод `sys.exit()`. При существовании субпроцессов отправляем им сигнал прерывания и если они не завершились - у
Это теперь привязано к языку реализации, что для архитектуры не очень

2022-02-05 11:53 UTC, yurii-litvinov commented on README.md
> +* Команда `external` - вызов внешних команд в случае, если введено что-то, что интерпретатор не знает. Создается новый поток, в котором выполняется процесс требуемой команды.  `stdin` передается либо
Ещё бывает поток ошибок, его тоже надо получать (да и вообще в шелле поддерживать). Например, компиляторы весь полезный вывод туда пишут :)

2022-02-05 11:53 UTC, yurii-litvinov commented on README.md
> +* Команда `exit` завершает работу интерпретатора, а именно в методе execute вызывается метод exit(). При существовании субпроцессов отправляем им сигнал прерывания и если они не завершились - убиваем
Это потому что IDE умная и запускает шелл отдельным процессом (возможно, как раз во избежание). Я же говорю про юзкейс, когда я просто хочу попользоваться вашим шеллом из внешней программы, без ухищрений. Мне было бы удобнее иметь гарантию, что мне после вызова Main либо вернут управление, либо выбросят исключение (то есть ваша система, даже будучи интегрирована как подсистема в другую программу, ведёт себя как обычная функция).

2022-02-05 11:53 UTC, yurii-litvinov requested changes
Надо ещё немного уточнить

2022-02-08 18:13 UTC, anchouls commented on README.md
> +Всё что находится в одинарных кавычках разбирается как есть и является строкой, а в двойных осуществляется проверка: содержится ли подстановка переменной (если есть, то происходит подстановка).
Кавычки имеют значение только при парсинге при определение типа строки. В дальнейшем они не имеют никакого значения и интерпретируются как обычный символ.

2022-02-11 18:21 UTC, annapotr commented
Документация дополнена.
@yurii-litvinov

2022-02-11 18:37 UTC, yurii-litvinov approved these changes
Да, теперь всё ок, зачтена.

2022-02-11 18:37 UTC, yurii-litvinov commented on README.md
> +чистая строка - строка, в которой нет подстановок, строка, объявление переменных `=`, `|` - пайплайны, конец строки.
А теперь тут чисто лингвистически нехорошо: у вас как бы список через запятую, но оборот "в которой нет подстановок" всё портит. А поскольку в архитектурной документации всё, что может быть понято неправильно, будет понято неправильно, это тоже проблема :)

2022-02-11 18:37 UTC, yurii-litvinov commented on README.md
> +`stdin` первой команды привязывается на время выполнения на `stdin` испольнительной системы (`python: sys.stdin`), `stdout` для последней команды соответствующе.
```suggestion
`stdin` первой команды привязывается на время выполнения на `stdin` исполнительной системы (`python: sys.stdin`), `stdout` для последней команды соответствующе.
```

2022-02-11 18:37 UTC, yurii-litvinov commented on README.md
> +* Команда `declaration` присваивает значение переменной. Соответственно, ее аргументы - название и значение переменной. Всё записывается в глобальный словарь `{"название переменной": "её вычесленное
```suggestion
* Команда `declaration` присваивает значение переменной. Соответственно, ее аргументы - название и значение переменной. Всё записывается в глобальный словарь `{"название переменной": "её вычисленное значение"}
```

2022-02-11 18:54 UTC, merged